version: 2

builds:
  - id: go-template-lsp
    main: ./cmd/go-template-lsp
    binary: go-template-lsp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: go-template-lsp
    builds:
      - go-template-lsp
    formats:
      - tar.gz
    name_template: "go-template-lsp_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
